@startuml harvester2.0 ERD 

skinparam linetype ortho

' ERD
card "Entity Relationship Diagram" as entities {
  entity "harvest_source" as source {
    uuid : uuid (PK)
    --
    name: text
    notifications_emails: array( txt )
    organization_name: txt
    frequency: text
    config: json
    urls: array( txt ) 
    schema_validation_type: text
  }

  entity "harvest_record" as record {
    uuid : uuid (PK)
    --
    source_id: uuid (FK)
    job_id: uuid (FK)
    status: text
    s3_path: text
  }

  entity "harvest_job" as job {
    uuid : uuid (PK)
    --
    source_id: uuid (FK)
    status: text
    date_created 
    date_finished: datetime
    extract_started: datetime
    extract_finished: datetime
    compare_started: datetime
    compare_finished: datetime
    records_added: smallint
    records_updated: smallint
    records_deleted: smallint
    records_errored: smallint
    records_ignored: smallint
  }

  entity "harvest_error" as error {
    uuid : uuid (PK)
    --
    job_id: uuid (FK)
    record_id: uuid (FK)
    record_reported_id: text
    date_created: datetime
    error_type: text
    severity: enum
    message: text

  }
}

' lookup tables
card "Lookup Tables" as lookup {
  
  entity "data_format" as data_format {
    name: text (PK)
    --
    mime_type: text
  }
}

' enumerators
card "Enumerators" as enumerators {

  enum error_severity {
    ERROR
    CRITICAL
  }

  enum job_status {
    CREATE
    PROCESSING
    COMPLETE
  }

  enum schema_validation {
    DCATUS
    ISO1911
  }

  enum record_status {
    STALE
    ACTIVE
    INVALID
  }
} 

' relationships
source ||--|{ job
source ||--|{ record
job ||--|{ record
job ||-|{ error

@enduml
