services:
  mdtranslator:
    image: ghcr.io/gsa/mdtranslator:latest
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-d", "{}", "-X", "POST", "http://localhost:3000/translates"]
      interval: 10s
      timeout: 10s
      retries: 5
  nginx-harvest-source:
    image: nginx
    volumes:
      - ./tests/harvest-sources:/usr/share/nginx/html
      - ./tests/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80  
  localstack-container:
    privileged: true
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:4566"]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"
  db:
      image: postgres:latest
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      ports:
        - "${DATABASE_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URI: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      FLASK_APP: run.py
      FLASK_ENV: development
    ports:
      - "8080:8080"
      - "5678:5678"
    command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --host=0.0.0.0 --port=8080

volumes:
  postgres_data: