FROM ghcr.io/apache/airflow/main/prod/python3.8:8f452822b556a1ff79d7d92d285596b89d0b789d

# set env vars
ENV _AIRFLOW_DB_MIGRATE=true
ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor
ENV AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=true

# soft WIP
ENV AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
ENV AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true

# active WIP
# ENV AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=128
# ENV AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD=240
# ENV AIRFLOW__CORE__MAX_MAP_LENGTH=2048
ENV AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=240
ENV AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
# ENV AIRFLOW__CORE__LOAD_EXAMPLES=True
ENV AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=480
# ENV AIRFLOW__SCHEDULER__MAX_DAGRUNS_TO_CREATE_PER_LOOP=1
# ENV AIRFLOW__CORE__CHECK_SLAS=False

# hostname troubleshooting
ENV AIRFLOW__WEBSERVER__EXPOSE_HOSTNAME=true
ENV AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT=8080
# ENV AIRFLOW__WEBSERVER__BASE_URL=https://airflow-test-webserver.app.cloud.gov:8080
ENV AIRFLOW__CORE__HOSTNAME_CALLABLE=airflow.utils.net.get_host_ip_address

# log permissions troubleshooting
# ENV AIRFLOW__LOGGING__REMOTE_LOGGING=true
# ENV AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://AKIAR7FXZINYCEVU6NFS:PLh9%2Bs0yZ2E99m0EsrBMF%2BvCAHS7yWcd7o99%2FZU4@s3-us-gov-west-1.amazonaws.com/cg-f35a8fc4-e48d-4cd9-9670-e5bc754fcac3
# ENV AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=aws-s3-conn

# inject POSTGRES_URI_STRING build arg into AIRFLOW__DATABASE__SQL_ALCHEMY_CONN env var
ARG AIRFLOW_POSTGRES_URI_STRING
ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW_POSTGRES_URI_STRING

# copy over dags folder
COPY --chown=airflow:root dags /opt/airflow/dags
