FROM ghcr.io/apache/airflow/main/prod/python3.8:8f452822b556a1ff79d7d92d285596b89d0b789d

# set env vars
ENV _AIRFLOW_DB_MIGRATE='true'
ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor
ENV AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
ENV AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=true
ENV AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true

# inject POSTGRES_URI_STRING build arg into AIRFLOW__DATABASE__SQL_ALCHEMY_CONN env var
ARG POSTGRES_URI_STRING
ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$POSTGRES_URI_STRING

# copy over dags folder
COPY --chown=airflow:root dags /opt/airflow/dags