"""DCAT-US 3 warning detection (GSA/data.gov#6127).

Warnings are semantic / content-quality signals that sit *above* schema
validation: they do not fail a record, they flag likely data-quality issues or
incomplete v1.1 -> v3 migrations. Each rule is a small pure function that takes
the offending value (and any sibling value a cross-field rule needs) and returns
a `DcatWarning`, or None when the value is fine. The entry point
`detect_dcat_warnings` walks a dataset record, dispatches each typed object to
its class rules, and returns a flat list of `DcatWarning` tuples.

Each warning carries a stable `warning_type` slug alongside its human-readable
message so the storage-wiring story can populate `harvest_record_error.type`
without parsing message text (mirroring how harvest errors are typed by
exception class name in `harvester/harvest.py`).

Boundary with the schema (GSA/data.gov#6243): a warning rule must never fire on
a value the DCAT-US 3.0 JSON Schema already rejects. The schema owns JSON type,
format, length, and enum checks; this module owns content-and-semantics checks
on values the schema accepts. When a rule below guards on `isinstance(...)` (or
similarly narrows its input) purely to defer to the schema, the guard's comment
names the schema constraint it is deferring to. Restating a schema constraint
here would report the same defect twice: once as a validator error, once as a
warning. If you add a rule, check the field's definition under
`schemas/dcatus3.0/definitions/` first and only warn on values the schema's
type/format/length/enum already lets through.

Known, accepted limitation: dropping the universal `@id` IRI walk (see below)
means an `@id` on an object nested under a property the schema does not
define (e.g. an ad hoc `extension` object) now produces no signal at all --
not a schema error, not a warning -- because the schema never validates that
object in the first place. We do not restore the universal walk: doing so
would reinstate the exact double-report this issue is about for every
schema-defined object (each definition declares `@id` as `{"type": "string",
"format": "iri"}`), and a position-aware version would need to track which
paths the schema actually covers, which this module does not do.

Rules that validate against controlled vocabularies (ISO 639-1 languages, IANA
character sets and media types, NARA restriction authority lists) read bundled
static JSON snapshots from `reference_data/` instead of calling those registries
at harvest time. Regenerate the machine-readable snapshots with
`scripts/refresh_dcat_reference_data.py`.

Rules follow the agreed spec: GSA/data.gov#6093 (comment 4799323747).
"""

import json
import re
from collections import Counter
from datetime import date, datetime
from pathlib import Path
from typing import NamedTuple, Optional

from jsonschema import FormatChecker

from harvester.utils.general_utils import is_number, translate_spatial

_REFERENCE_DATA_DIR = Path(__file__).resolve().parent / "reference_data"


class DcatWarning(NamedTuple):
    """A detected content-quality warning: a stable type slug + a message."""

    warning_type: str
    message: str


def _load_reference_values(filename: str, *keys) -> frozenset:
    """Load a snapshot's `values` list as a lowercased frozenset.

    Reference data is bundled as static JSON (regenerated by
    scripts/refresh_dcat_reference_data.py) so warning detection never makes a
    network call in the harvest path. `keys` drills into nested sections (used
    by the NARA lists, which group several authority lists in one file).
    """
    with open(_REFERENCE_DATA_DIR / filename) as f:
        data = json.load(f)
    for key in keys:
        data = data[key]
    return frozenset(value.lower() for value in data["values"])


_ISO_639_1_CODES = _load_reference_values("iso639_1_language_codes.json")
_IANA_CHARACTER_SETS = _load_reference_values("iana_character_sets.json")
_IANA_MEDIA_TYPES = _load_reference_values("iana_media_types.json")
_NARA_ACCESS_RESTRICTION_STATUS = _load_reference_values(
    "nara_restrictions.json", "access_restriction_status"
)
_NARA_SPECIFIC_ACCESS_RESTRICTION = _load_reference_values(
    "nara_restrictions.json", "specific_access_restriction"
)
_NARA_USE_RESTRICTION_STATUS = _load_reference_values(
    "nara_restrictions.json", "use_restriction_status"
)
_NARA_SPECIFIC_USE_RESTRICTION = _load_reference_values(
    "nara_restrictions.json", "specific_use_restriction"
)


# xsd:duration / ISO 8601 duration. Requires something after P (and after T
# when a time part is present); accepts an optional leading sign and weeks.
_XSD_DURATION_RE = re.compile(
    r"^-?P(?!$)(\d+Y)?(\d+M)?(\d+W)?(\d+D)?(T(?!$)(\d+H)?(\d+M)?(\d+(\.\d+)?S)?)?$"
)

# spatialResolutionInMeters: digits with an optional decimal point. A leading
# sign is allowed through so negative values still reach the "> zero" check
# rather than being reported as non-numeric; unlike is_number this rejects
# float-parseable non-numbers such as "1e3", "inf", and "nan".
_DECIMAL_RE = re.compile(r"^-?\d+(\.\d+)?$")

# Message tails for the shared temporalResolution check. The spec words the
# Dataset case as ISO 8601 and the Distribution/DataService case as xsd:duration
# even though they share the same grammar.
_ISO_8601_DURATION_MSG = (
    'does not appear to be a valid ISO 8601 duration (e.g., "P1Y", "P6M", "P1D").'
)
_XSD_DURATION_MSG = "does not appear to be a valid xsd:duration."

# Legacy DCAT-US 1.1 accessLevel terms that should have been migrated to a v3
# accessRights value.
_LEGACY_ACCESS_LEVEL_TERMS = {"restricted public", "non-public"}

# Country-name spellings we treat as "US" for postal-code validation.
_US_COUNTRY_NAMES = {
    "us",
    "usa",
    "u.s.",
    "u.s.a.",
    "united states",
    "united states of america",
}

# Used by `_parse_dcat_date` to defer to the validator's own definition of a
# valid "date"/"date-time" (the validator itself is built with
# `format_checker=FormatChecker()`, see `build_dcatus3_validator`). This is
# not restating a schema constraint -- it is asking the schema's own checker
# whether a value is in-bounds before treating it as a parsed date, so a
# value the schema rejects (e.g. a date-time with no UTC offset) can't also
# be double-reported as a `date_out_of_order` warning (GSA/data.gov#6243).
_DATE_FORMAT_CHECKER = FormatChecker()


def _parse_dcat_date(value):
    """Parse a DCAT date/date-time/YYYY/YYYY-MM string to a date, else None.

    A `created`/`modified`/`issued`/etc. value is `anyOf[null, {format:
    date-time}, {format: date}, {pattern: "^[0-9]{4}$"}, {pattern:
    "^[0-9]{4}-[0-9]{2}$"}]` (see e.g. Dataset.json `created`). Only that
    exact set parses here; anything else is already a schema error, not a
    content-quality one. `format: date-time` is RFC 3339 and requires a UTC
    offset, which `datetime.fromisoformat` alone does not enforce, so the
    date-time branch below checks `FormatChecker` first rather than relying
    on `fromisoformat` succeeding.

    Every one of those alternatives is checked by the schema against the
    value exactly as given -- the `^[0-9]{4}$`/`^[0-9]{4}-[0-9]{2}$` patterns
    are anchored with no allowance for surrounding whitespace, and both
    `FormatChecker` formats reject it too. So this parses `value` itself, not
    a stripped copy: a padded string like `" 2025-06-01 "` is already a
    schema `format`/`pattern` error (GSA/data.gov#6243), and stripping it
    here would let it parse anyway and be double-reported as
    `date_out_of_order`.
    """
    if not isinstance(value, str):
        return None
    try:
        if re.fullmatch(r"\d{4}", value):
            return date(int(value), 1, 1)
        if re.fullmatch(r"\d{4}-\d{2}", value):
            year, month = value.split("-")
            return date(int(year), int(month), 1)
        if _DATE_FORMAT_CHECKER.conforms(value, "date"):
            return date.fromisoformat(value)
        if _DATE_FORMAT_CHECKER.conforms(value, "date-time"):
            # RFC 3339 (what `format: date-time` requires) treats the "T"
            # separator and the "Z" UTC designator as case-insensitive, and
            # `FormatChecker` -- and therefore the schema -- accepts a
            # lowercase "z" for the same reason it accepts a lowercase "t"
            # (which `fromisoformat` already tolerates on its own). Only a
            # trailing, case-insensitive "z" needs normalizing to the offset
            # `fromisoformat` requires; anywhere else in a valid date-time
            # string, "Z"/"z" can't appear. Leaving this schema-valid form
            # unparseable would mean no `date_out_of_order` warning could
            # ever fire for it (GSA/data.gov#6243).
            normalized = re.sub(r"[Zz]$", "+00:00", value)
            return datetime.fromisoformat(normalized).date()
    except ValueError:
        # `conforms()` accepts some values (e.g. a pattern-only "0000" year)
        # that the stricter parse below still rejects; treat those as
        # unparseable rather than raising out of warning detection, matching
        # this function's pre-6243 behavior.
        return None
    return None


def _date_later_than(value, other) -> bool:
    """True when both values parse to dates and value is strictly after other."""
    parsed_value = _parse_dcat_date(value)
    parsed_other = _parse_dcat_date(other)
    if parsed_value is None or parsed_other is None:
        return False
    return parsed_value > parsed_other


def _warn_duplicate_keywords(keywords) -> list:
    """Warn once per keyword that appears more than once.

    Empty entries are skipped: `keyword` items carry `minLength: 1`, so ""
    is already a schema violation, not a content-quality one. Whitespace-only
    entries pass that constraint, so they are still counted here.
    """
    if not isinstance(keywords, list):
        return []
    counts = Counter(k for k in keywords if isinstance(k, str) and k != "")
    return [
        DcatWarning(
            "duplicate_keyword",
            f'Duplicate keyword detected: "{value}". Keywords should be unique.',
        )
        for value, count in counts.items()
        if count > 1
    ]


def _warn_spatial_resolution(value) -> Optional[DcatWarning]:
    """Warn if spatialResolutionInMeters is non-numeric or not greater than zero."""
    if value is None:
        return None
    # spatialResolutionInMeters is `type: ["null", "string"]`; a non-string
    # value is already a schema type error, not a content-quality one.
    if not isinstance(value, str):
        return None
    if not _DECIMAL_RE.match(value):
        return DcatWarning(
            "invalid_spatial_resolution",
            f'`spatialResolutionInMeters` value "{value}" '
            "does not appear to be a valid number.",
        )
    if float(value) <= 0:
        return DcatWarning(
            "invalid_spatial_resolution",
            f'`spatialResolutionInMeters` value "{value}" must be greater than zero.',
        )
    return None


def _warn_temporal_resolution(value, invalid_msg: str) -> Optional[DcatWarning]:
    """Warn if temporalResolution is not a valid duration.

    `invalid_msg` supplies the class-specific message tail (ISO 8601 for Dataset,
    xsd:duration for Distribution/DataService); the grammar checked is identical.
    """
    if value is None:
        return None
    # temporalResolution is `type: ["null", "string"]`; a non-string value is
    # already a schema type error, not a content-quality one.
    if not isinstance(value, str):
        return None
    if _XSD_DURATION_RE.match(value):
        return None
    return DcatWarning(
        "invalid_temporal_resolution",
        f'`temporalResolution` value "{value}" {invalid_msg}',
    )


def _warn_byte_size(value) -> Optional[DcatWarning]:
    """Warn if byteSize does not parse to a number."""
    if value is None:
        return None
    # byteSize is `type: ["null", "string"]`; a non-string value (e.g. a list)
    # is already a schema type error. is_number() would otherwise raise
    # TypeError on non-string/non-numeric values such as a list.
    if not isinstance(value, str):
        return None
    if is_number(value):
        return None
    return DcatWarning(
        "invalid_byte_size",
        f'`byteSize` value "{value}" does not appear to be a valid number.',
    )


def _warn_legacy_access_rights(value) -> Optional[DcatWarning]:
    """Warn if accessRights is a legacy v1.1 accessLevel term."""
    if isinstance(value, str) and value.strip().lower() in _LEGACY_ACCESS_LEVEL_TERMS:
        return DcatWarning(
            "legacy_access_rights",
            f'`accessRights` value "{value}" appears to be a legacy DCAT-US 1.1 '
            "`accessLevel` term. Migrate to an appropriate DCAT-US 3 access "
            "rights value.",
        )
    return None


def _warn_created_after(created, modified, issued) -> list:
    """Warn if created is later than modified or issued, where each is present."""
    warnings = []
    for other_field, other_value in (("modified", modified), ("issued", issued)):
        if other_value is not None and _date_later_than(created, other_value):
            warnings.append(
                DcatWarning(
                    "date_out_of_order",
                    f'`created` value "{created}" is later than `{other_field}` '
                    f'value "{other_value}". A dataset cannot be created after it '
                    "was modified or issued.",
                )
            )
    return warnings


def _warn_issued_after_modified(issued, modified) -> Optional[DcatWarning]:
    """Warn if issued is later than modified, where modified is present."""
    if modified is not None and _date_later_than(issued, modified):
        return DcatWarning(
            "date_out_of_order",
            f'`issued` value "{issued}" is later than `modified` value '
            f'"{modified}". A dataset cannot be issued after it was last modified.',
        )
    return None


def _warn_period_start_after_end(start, end) -> Optional[DcatWarning]:
    """Warn if a PeriodOfTime startDate is later than its endDate."""
    if start is not None and end is not None and _date_later_than(start, end):
        return DcatWarning(
            "date_out_of_order",
            f'`startDate` value "{start}" is later than `endDate` value "{end}". '
            "The start of a time period cannot be after its end.",
        )
    return None


def _warn_tel_has_letters(value) -> Optional[DcatWarning]:
    """Warn if a tel value contains letters."""
    if isinstance(value, str) and re.search(r"[A-Za-z]", value):
        return DcatWarning(
            "invalid_tel",
            f'`tel` value "{value}" contains letters and may not be a valid '
            "telephone number.",
        )
    return None


def _warn_expected_data_type(value) -> Optional[DcatWarning]:
    """Warn if expectedDataType does not begin with `xsd:`."""
    # Metric.expectedDataType is `"type": "string"`, a scalar; a non-string
    # value (e.g. a list) is already a schema type error.
    if not isinstance(value, str):
        return None
    if not value.startswith("xsd:"):
        return DcatWarning(
            "invalid_expected_data_type",
            f'`expectedDataType` value "{value}" does not appear to be a '
            'valid XSD type. Expected format begins with "xsd:" (e.g., '
            '"xsd:string", "xsd:decimal").',
        )
    return None


def _warn_spatial_unresolved(field: str, value) -> Optional[DcatWarning]:
    """Warn if a spatial value cannot be resolved to a geographic area.

    `bbox` and `geometry` are each `anyOf[null, string, object]`
    (Location.json), and the object variant requires "type" and
    "coordinates" for both. A value that is neither a string nor a dict
    carrying those required keys is already a schema type/required-property
    error for either field, not a content-quality one, so it is skipped here
    rather than re-warned on.

    `bbox`'s object variant additionally pins "type" to the constant
    "Polygon"; an object whose "type" isn't exactly "Polygon" is already a
    schema `const` error there, so it is skipped too (GSA/data.gov#6243) --
    `translate_spatial` never gets the chance to judge it. `geometry`'s
    object variant has no such constant (any "type" value passes the
    schema), so a `geometry` dict `translate_spatial` can't resolve is still
    a legitimate, schema-clean content-quality warning and must still fire.
    """
    if value is None:
        return None
    if not isinstance(value, (str, dict)):
        return None
    if isinstance(value, dict):
        if not {"type", "coordinates"} <= value.keys():
            return None
        if field == "bbox" and value.get("type") != "Polygon":
            return None
    if translate_spatial(value):
        return None
    return DcatWarning(
        "unresolvable_spatial_value",
        f'spatial value "{value}" could not be resolved to a recognized '
        "geographic area.",
    )


def _warn_us_postal_code(postal_code, country_name) -> Optional[DcatWarning]:
    """Warn if a US address postal code contains letters."""
    is_us = (
        isinstance(country_name, str)
        and country_name.strip().lower() in _US_COUNTRY_NAMES
    )
    if is_us and isinstance(postal_code, str) and re.search(r"[A-Za-z]", postal_code):
        return DcatWarning(
            "invalid_postal_code",
            f'Postal code "{postal_code}" contains letters, which is not valid '
            "for a US address.",
        )
    return None


def _warn_empty_address(address: dict) -> Optional[DcatWarning]:
    """Warn if an Address object has no populated fields.

    Each Address field is `type: ["null", "string"]` (Address.json), so
    `None` and "" are the only schema-valid "unpopulated" states. Any other
    falsy value (e.g. `0`, `[]`) is already a schema type error, not an
    empty-address content issue -- there is a populated, if wrongly-typed,
    value, so it must not also count toward "no populated fields".
    """
    fields = (
        "street-address",
        "locality",
        "region",
        "postal-code",
        "country-name",
    )
    if all(address.get(field) in (None, "") for field in fields):
        return DcatWarning("empty_address", "Address object has no populated fields.")
    return None


def _warn_cui_banner_marking(value) -> Optional[DcatWarning]:
    """Warn if a CUI banner marking does not follow the expected format."""
    if isinstance(value, str) and not value.startswith("CUI//"):
        return DcatWarning(
            "invalid_cui_banner_marking",
            f'`cuiBannerMarking` value "{value}" does not appear to follow the CUI '
            'banner marking format. Expected format begins with "CUI//".',
        )
    return None


def _as_list(value) -> list:
    """Normalize a scalar-or-array field to a list (None -> empty)."""
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def _warn_language(value) -> list:
    """Warn on language codes that are too short or not recognized ISO 639-1.

    `language` is `anyOf[null, {string, maxLength 2}, {array of {string,
    maxLength 2}}]`, so `language` may be a single string or an array of
    strings; either way each entry is expected to already be at most 2
    characters. An entry longer than 2 characters is already a schema
    `maxLength` error, so it is skipped here rather than re-warned on.
    """
    warnings = []
    for entry in _as_list(value):
        if not isinstance(entry, str) or len(entry) > 2:
            continue
        if len(entry) < 2:
            warnings.append(
                DcatWarning(
                    "invalid_language",
                    f'`language` value "{entry}" is too short to be a valid '
                    "language code. ISO 639-1 codes are 2 characters.",
                )
            )
        elif entry.lower() not in _ISO_639_1_CODES:
            warnings.append(
                DcatWarning(
                    "invalid_language",
                    f'`language` value "{entry}" is not a recognized ISO 639-1 '
                    "language code.",
                )
            )
    return warnings


def _warn_character_encoding(value) -> list:
    """Warn on character encodings not recognized as IANA character set names."""
    # Distribution.characterEncoding is `anyOf[null, {array of string}]`; a
    # bare string (not wrapped in a list) is already a schema type error, so
    # only a list is evaluated here (unlike `_warn_language`, no `_as_list`).
    if not isinstance(value, list):
        return []
    warnings = []
    for entry in value:
        if isinstance(entry, str) and entry.lower() not in _IANA_CHARACTER_SETS:
            warnings.append(
                DcatWarning(
                    "invalid_character_encoding",
                    f'`characterEncoding` value "{entry}" is not a recognized IANA '
                    "character set name.",
                )
            )
    return warnings


def _warn_media_type(value) -> Optional[DcatWarning]:
    """Warn if a mediaType is not from the IANA media types registry.

    A media type may carry parameters (e.g. "text/csv; charset=UTF-8"); the
    registry lists bare type/subtype only, so match on the portion before the
    first ";".
    """
    if not isinstance(value, str):
        return None
    essence = value.split(";", 1)[0].strip()
    if essence.lower() not in _IANA_MEDIA_TYPES:
        return DcatWarning(
            "invalid_media_type",
            f'`mediaType` value "{value}" is not a recognized IANA media type.',
        )
    return None


def _restriction_value(value) -> Optional[str]:
    """Read a restriction as a string, or a Concept object's prefLabel."""
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        label = value.get("prefLabel")
        if isinstance(label, str):
            return label
    return None


def _warn_restriction(
    warning_type: str, field: str, value, authority, term: str
) -> Optional[DcatWarning]:
    """Warn if a restriction value is not in its NARA authority list.

    Accepts a bare string or a Concept object (checks its prefLabel). `term`
    names the authority in the message (e.g. "NARA access restriction status").
    """
    resolved = _restriction_value(value)
    if resolved is not None and resolved.lower() not in authority:
        return DcatWarning(
            warning_type,
            f'`{field}` value "{resolved}" is not a recognized {term} term.',
        )
    return None


def _append(warnings: list, result) -> None:
    """Append a single optional warning or extend with a list of warnings."""
    if result is None:
        return
    if isinstance(result, list):
        warnings.extend(result)
    else:
        warnings.append(result)


def _dataset_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_duplicate_keywords(obj.get("keyword")))
    _append(warnings, _warn_spatial_resolution(obj.get("spatialResolutionInMeters")))
    _append(
        warnings,
        _warn_temporal_resolution(
            obj.get("temporalResolution"), _ISO_8601_DURATION_MSG
        ),
    )
    _append(warnings, _warn_legacy_access_rights(obj.get("accessRights")))
    _append(
        warnings,
        _warn_created_after(obj.get("created"), obj.get("modified"), obj.get("issued")),
    )
    _append(
        warnings,
        _warn_issued_after_modified(obj.get("issued"), obj.get("modified")),
    )
    _append(warnings, _warn_language(obj.get("language")))
    return warnings


def _distribution_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_byte_size(obj.get("byteSize")))
    _append(warnings, _warn_spatial_resolution(obj.get("spatialResolutionInMeters")))
    _append(
        warnings,
        _warn_temporal_resolution(obj.get("temporalResolution"), _XSD_DURATION_MSG),
    )
    _append(warnings, _warn_character_encoding(obj.get("characterEncoding")))
    _append(warnings, _warn_media_type(obj.get("mediaType")))
    _append(warnings, _warn_language(obj.get("language")))
    return warnings


def _dataservice_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_spatial_resolution(obj.get("spatialResolutionInMeters")))
    _append(
        warnings,
        _warn_temporal_resolution(obj.get("temporalResolution"), _XSD_DURATION_MSG),
    )
    _append(warnings, _warn_language(obj.get("language")))
    return warnings


def _document_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_media_type(obj.get("mediaType")))
    return warnings


def _access_restriction_warnings(obj: dict) -> list:
    warnings = []
    _append(
        warnings,
        _warn_restriction(
            "invalid_restriction_status",
            "restrictionStatus",
            obj.get("restrictionStatus"),
            _NARA_ACCESS_RESTRICTION_STATUS,
            "NARA access restriction status",
        ),
    )
    _append(
        warnings,
        _warn_restriction(
            "invalid_specific_restriction",
            "specificRestriction",
            obj.get("specificRestriction"),
            _NARA_SPECIFIC_ACCESS_RESTRICTION,
            "NARA specific access restriction",
        ),
    )
    return warnings


def _use_restriction_warnings(obj: dict) -> list:
    warnings = []
    _append(
        warnings,
        _warn_restriction(
            "invalid_restriction_status",
            "restrictionStatus",
            obj.get("restrictionStatus"),
            _NARA_USE_RESTRICTION_STATUS,
            "NARA use restriction status",
        ),
    )
    _append(
        warnings,
        _warn_restriction(
            "invalid_specific_restriction",
            "specificRestriction",
            obj.get("specificRestriction"),
            _NARA_SPECIFIC_USE_RESTRICTION,
            "NARA specific use restriction",
        ),
    )
    return warnings


def _kind_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_tel_has_letters(obj.get("tel")))
    return warnings


def _location_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_spatial_unresolved("bbox", obj.get("bbox")))
    _append(warnings, _warn_spatial_unresolved("geometry", obj.get("geometry")))
    return warnings


def _metric_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_expected_data_type(obj.get("expectedDataType")))
    return warnings


def _period_of_time_warnings(obj: dict) -> list:
    warnings = []
    _append(
        warnings,
        _warn_period_start_after_end(obj.get("startDate"), obj.get("endDate")),
    )
    return warnings


def _address_warnings(obj: dict) -> list:
    warnings = []
    _append(
        warnings,
        _warn_us_postal_code(obj.get("postal-code"), obj.get("country-name")),
    )
    _append(warnings, _warn_empty_address(obj))
    return warnings


def _cui_restriction_warnings(obj: dict) -> list:
    warnings = []
    _append(warnings, _warn_cui_banner_marking(obj.get("cuiBannerMarking")))
    return warnings


# Maps a DCAT-US 3 @type to the rule function for that class. Adding a class is
# a one-line addition here plus its rule function above.
_TYPE_RULES = {
    "Dataset": _dataset_warnings,
    "Distribution": _distribution_warnings,
    "DataService": _dataservice_warnings,
    "Document": _document_warnings,
    "Kind": _kind_warnings,
    "Location": _location_warnings,
    "Metric": _metric_warnings,
    "PeriodOfTime": _period_of_time_warnings,
    "Address": _address_warnings,
    "CUIRestriction": _cui_restriction_warnings,
    "AccessRestriction": _access_restriction_warnings,
    "UseRestriction": _use_restriction_warnings,
}


def _walk_objects(node):
    """Yield every dict nested anywhere within a record (depth-first)."""
    if isinstance(node, dict):
        yield node
        for value in node.values():
            yield from _walk_objects(value)
    elif isinstance(node, list):
        for item in node:
            yield from _walk_objects(item)


def detect_dcat_warnings(data: dict) -> list:
    """Detect DCAT-US 3 content-quality warnings in a dataset record.

    Walks the record and dispatches each typed object to its class rules.
    Returns a flat list of `DcatWarning` tuples (empty when the record is
    clean). There is no universal `@id`/IRI check here: every DCAT-US 3
    definition declares `@id` as `{"type": "string", "format": "iri"}`, so an
    invalid IRI is already a schema `format` error (GSA/data.gov#6243).
    """
    warnings = []
    for obj in _walk_objects(data):
        type_value = obj.get("@type")
        # `@type` is `{"type": "string", ...}` in every DCAT-US 3 definition;
        # a non-string `@type` (e.g. a list or dict from a malformed record)
        # is already a schema type error, not a content-quality one. It is
        # also unhashable, so `_TYPE_RULES.get` would raise `TypeError:
        # unhashable type` on it if dispatched anyway.
        if not isinstance(type_value, str):
            continue
        rule = _TYPE_RULES.get(type_value)
        if rule is not None:
            _append(warnings, rule(obj))
    return warnings
