version: "3"

services:
  nginx-harvest-source:
    image: nginx
    volumes:
      - ./tests/harvest-sources:/usr/share/nginx/html
      - ./tests/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  localstack-container:
    privileged: true
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:4566"]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
