"""Add organization aliases

Revision ID: 1c80316df048
Revises: c69d6790efff
Create Date: 2025-11-14 19:13:05.929225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c80316df048"
down_revision = "c69d6790efff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.add_column(sa.Column("aliases", sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.drop_column("aliases")
    # ### end Alembic commands ###
