"""Add parent_identifier to record

Revision ID: 416319f5e5bb
Revises: 5416f9f5f06d
Create Date: 2025-09-19 19:09:44.757715

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "416319f5e5bb"
down_revision = "5416f9f5f06d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_identifier", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_record", schema=None) as batch_op:
        batch_op.drop_column("parent_identifier")

    # ### end Alembic commands ###
