"""Add code_repo_url and code_repo_exempt to organization

Revision ID: 428e3ffa02ea
Revises: f8d4c5ec0e5b
Create Date: 2026-08-13 10:35:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "428e3ffa02ea"
down_revision = "f8d4c5ec0e5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code_repo_url", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "code_repo_exempt",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.drop_column("code_repo_exempt")
        batch_op.drop_column("code_repo_url")
    # ### end Alembic commands ###
