"""add send_report_email to harvest_source

Revision ID: 5b9b5ccf2e34
Revises: d7e4b8c1a2f0
Create Date: 2026-09-04 17:00:48.604308

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b9b5ccf2e34"
down_revision = "d7e4b8c1a2f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "send_report_email",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.drop_column("send_report_email")

    # ### end Alembic commands ###
