"""adds records_total to harvest_job

Revision ID: 63a1161d69b7
Revises: 31663584b0de
Create Date: 2025-02-27 17:53:55.469668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a1161d69b7'
down_revision = '31663584b0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_job', schema=None) as batch_op:
        batch_op.drop_column('records_total')

    # ### end Alembic commands ###
