"""remove 'csdgm' from schema_type

Revision ID: a6aa1afd27b7
Revises: 1800d355e5b9
Create Date: 2025-09-12 17:06:56.439448

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aa1afd27b7'
down_revision = '1800d355e5b9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('iso19115_1', 'iso19115_2', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type_new').create(op.get_bind())
    with op.batch_alter_table('harvest_source', schema=None) as batch_op:
        batch_op.alter_column('schema_type',
               existing_type=postgresql.ENUM('iso19115_1', 'iso19115_2', 'csdgm', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type'),
               type_=sa.Enum('iso19115_1', 'iso19115_2', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type_new'),
               existing_nullable=False,
               postgresql_using='schema_type::text::schema_type_new')

    sa.Enum('iso19115_1', 'iso19115_2', 'csdgm', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('iso19115_1', 'iso19115_2', 'csdgm', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type').create(op.get_bind())
    with op.batch_alter_table('harvest_source', schema=None) as batch_op:
        batch_op.alter_column('schema_type',
               existing_type=sa.Enum('iso19115_1', 'iso19115_2', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type_new'),
               type_=postgresql.ENUM('iso19115_1', 'iso19115_2', 'csdgm', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type'),
               existing_nullable=False)

    sa.Enum('iso19115_1', 'iso19115_2', 'dcatus1.1: federal', 'dcatus1.1: non-federal', name='schema_type_new').drop(op.get_bind())
    # ### end Alembic commands ###