"""Update cascade delete for HarvestRecord

Revision ID: af16bb5a8d40
Revises: 31663584b0de
Create Date: 2025-02-19 12:32:55.626966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af16bb5a8d40'
down_revision = '31663584b0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_record_error', schema=None) as batch_op:
        batch_op.alter_column('harvest_record_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('harvest_job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_record_error', schema=None) as batch_op:
        batch_op.alter_column('harvest_job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('harvest_record_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
