"""Add notification_frequency

Revision ID: c04b66d4d5b9
Revises: 
Create Date: 2025-02-07 09:55:49.013498

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c04b66d4d5b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "notification_frequency",
                sa.Enum("on_error", "always", name="notification_frequency"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.drop_column("notification_frequency")

    # ### end Alembic commands ###
