"""Add description field to harvest_source

Revision ID: cd1b89204949
Revises: 5b9b5ccf2e34
Create Date: 2026-09-23 08:40:51.659016

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd1b89204949"
down_revision = "5b9b5ccf2e34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_harvest_source_description"), ["description"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_harvest_source_description"))
        batch_op.drop_column("description")

    # ### end Alembic commands ###
