"""Add new waf-collection harvest source type

Revision ID: d805537d4cf2
Revises: 1800d355e5b9
Create Date: 2025-09-15 16:21:16.111414

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d805537d4cf2"
down_revision = "1800d355e5b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("collection_parent_url", sa.String(), nullable=True)
        )
        batch_op.execute("ALTER TYPE source_type ADD VALUE 'waf-collection'")
        batch_op.alter_column(
            "source_type",
            type_=sa.Enum("document", "waf", "waf-collection", name="source_type"),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_source", schema=None) as batch_op:
        batch_op.drop_column("collection_parent_url")
        batch_op.execute("ALTER TYPE source_type DROP VALUE 'waf-collection'")
        batch_op.alter_column(
            "source_type", type_=sa.Enum("document", "waf", name="source_type")
        )

    # ### end Alembic commands ###
