"""add error and update notification type

Revision ID: e75e287e2251
Revises: 5416f9f5f06d
Create Date: 2025-09-23 14:46:49.235190

"""

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from migrations.utils import get_terminate_processes_sql_cmd


# revision identifiers, used by Alembic.
revision = "e75e287e2251"
down_revision = "5416f9f5f06d"
branch_labels = None
depends_on = None

terminate_processes_sql = get_terminate_processes_sql_cmd()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(terminate_processes_sql)

    op.sync_enum_values(
        enum_schema="public",
        enum_name="notification_frequency",
        new_values=["on_error", "always", "on_error_or_update"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="harvest_source",
                column_name="notification_frequency",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(terminate_processes_sql)

    op.sync_enum_values(
        enum_schema="public",
        enum_name="notification_frequency",
        new_values=["on_error", "always"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="harvest_source",
                column_name="notification_frequency",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
