"""Add dcatus_catalog to harvest_job

Revision ID: f8d4c5ec0e5b
Revises: e2356e60edfb
Create Date: 2026-07-29 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f8d4c5ec0e5b"
down_revision = "e2356e60edfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("dcatus_catalog", postgresql.JSONB(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("harvest_job", schema=None) as batch_op:
        batch_op.drop_column("dcatus_catalog")

    # ### end Alembic commands ###
