# talk to the right internal app
map $server_name $internal_url {
  default {{env "INTERNAL_ROUTE"}};
}

# GSA/data.gov#6293: validator paths are proxied to their own internal app
map $server_name $validator_internal_url {
  default {{env "VALIDATOR_INTERNAL_ROUTE"}};
}

map $auth_enabled $apply_auth {
  default on;
  "true"  on;
  "false" off;
}
