# use 'listen 80 deferred;' for Linux
# use 'listen 80 accept_filter=httpready;' for FreeBSD
listen {{port}};

keepalive_timeout 5;

# path for static files
root ./public;

# simplify redirect with relative path
absolute_redirect off;

location / {
  # checks for static file, if not found proxy to app
  try_files $uri @proxy_to_app;
}

location @proxy_to_app {
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_redirect off;
  set $backend_servers $internal_url:61443;
  proxy_pass https://${backend_servers}${request_uri};
}

proxy_intercept_errors on;
error_page 500 502 504 /500.html;
location = /500.html {
  root ./public;
}

error_page 403 /403.html;
location = /403.html {
  root ./public;
}

# Don't leak any server information in response headers
server_tokens off;
