# block malicious requests detected by AWS WAF
# https://github.com/GSA/data.gov/issues/5236

# return 429 for any non-empty X-Amzn-Waf-Detection header value
if ($http_x_amzn_waf_detection != "") {
  return 429;
}

error_page 429 @malicious;

location @malicious {
  rewrite ^(.*)$ /malicious.html break;
}
location = /malicious.html {
  root ./public;
}
