name: E2E Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Write Playwright Auth File
      run: |
        cat << EOF > ./pytest_state.json
        ${{ secrets.PLAYWRIGHT_AUTH_JSON }}
        EOF
    - name: Run E2E tests
      run: make test-ci
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: e2e-report
        path: e2e-report/
        retention-days: 30
