name: Load Test
on:
  workflow_dispatch:
env:
  PY_VERSION: "3.10"
  POETRY_VERSION: "1.7.1"

jobs:
  load-test:
    name: H2.0 Load Test
    runs-on: ubuntu-latest
    env:
      FOO_VAR: ${{vars.FOO_VAR}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PY_VERSION }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
            poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install Dependencies
        run: |
            poetry env use ${{ env.PY_VERSION }}
            poetry install

      - name: Run Load Test
        env:
            SRC_TITLE: 'EPA ScienceHub'
            SRC_URL: 'https://pasteur.epa.gov/metadata.json'
            SRC_OWNER_ORG: '82b85475-f85d-404a-b95b-89d1a42e9f6b'
            SRC_SOURCE_TYPE: 'datajson'
            CKAN_URL: ${{secrets.CKAN_URL_STAGING}}
            CKAN_API_TOKEN: ${{secrets.CKAN_API_TOKEN_STAGING}}
        run: |
            poetry run python scripts/fake.py