name: DB/CKAN Sync Script

env:
  PY_VERSION: "3.13"
  POETRY_VERSION: "2.0.0"

on:
  workflow_dispatch:
    inputs: 
      dry_run:
        description: 'Run the sync in dry run mode.'
        required: true
        type: boolean
        default: true
      preview:
        description: 'Preview stats before running the sync.'
        required: true
        type: boolean
        default: true

jobs:
  run-sync:
    env:
        DATABASE_URI: ${{secrets.DATABASE_URI}}
        CKAN_API_TOKEN: ${{secrets.CKAN_API_TOKEN}}
        CKAN_API_URL: ${{secrets.CKAN_API_URL}}
    runs-on: ubuntu-latest
    name: Sync
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install Dependencies
        run: |
          poetry env use ${{ env.PY_VERSION }}
          poetry install
      
      - name: Run QA
        run: |
          args=''
          if ${{ inputs.dry_run }}; then
            args="${args} --dry_run"
          fi

          if ${{ inputs.preview }}; then
            args="${args} --preview"
          fi

          poetry run python ./scripts/sync_db.py ${args}